<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

class DummyPermissionSeeder extends Seeder
{
    /**
     * Seed additional demo permissions for the admin screens.
     */
    public function run(): void
    {
        $permissions = [
            ['name' => 'recruitment.view-candidates', 'group_name' => 'recruitment'],
            ['name' => 'recruitment.schedule-interviews', 'group_name' => 'recruitment'],
            ['name' => 'finance.approve-expenses', 'group_name' => 'finance'],
            ['name' => 'finance.process-reimbursements', 'group_name' => 'finance'],
            ['name' => 'performance.review-team', 'group_name' => 'performance'],
            ['name' => 'performance.approve-goals', 'group_name' => 'performance'],
            ['name' => 'onboarding.manage-checklists', 'group_name' => 'onboarding'],
            ['name' => 'onboarding.assign-buddy', 'group_name' => 'onboarding'],
            ['name' => 'employee.create', 'group_name' => 'employee'],
            ['name' => 'employee.edit', 'group_name' => 'employee'],
            ['name' => 'employee.delete', 'group_name' => 'employee'],
            ['name' => 'employee.view', 'group_name' => 'employee'],
            ['name' => 'employee.export', 'group_name' => 'employee'],
            ['name' => 'employee.import', 'group_name' => 'employee'],
            ['name' => 'employee.manage-roles', 'group_name' => 'employee'],
            ['name' => 'employee.manage-permissions', 'group_name' => 'employee'],
            ['name' => 'employee.view-activity-logs', 'group_name' => 'employee'],
            ['name' => 'employee.manage-departments', 'group_name' => 'employee'],
            ['name' => 'employee.manage-teams', 'group_name' => 'employee'],
            ['name' => 'employee.manage-salaries', 'group_name' => 'employee'],
            ['name' => 'employee.manage-benefits', 'group_name' => 'employee'],
            ['name' => 'employee.manage-attendance', 'group_name' => 'employee'],
            ['name' => 'employee.manage-leave', 'group_name' => 'employee'],
            ['name' => 'leave.create', 'group_name' => 'leave'],
            ['name' => 'leave.edit', 'group_name' => 'leave'],
            ['name' => 'leave.delete', 'group_name' => 'leave'],
            ['name' => 'leave.view', 'group_name' => 'leave'],
            ['name' => 'leave.approve', 'group_name' => 'leave'],
            ['name' => 'leave.reject', 'group_name' => 'leave'],
            ['name' => 'leave.cancel', 'group_name' => 'leave'],
            ['name' => 'leave.export', 'group_name' => 'leave'],
            ['name' => 'leave.import', 'group_name' => 'leave'],
            ['name' => 'leave.manage-types', 'group_name' => 'leave'],
            ['name' => 'leave.manage-policies', 'group_name' => 'leave'],
            ['name' => 'leave.view-reports', 'group_name' => 'leave'],
            ['name' => 'leave.manage-approvers', 'group_name' => 'leave'],
            ['name' => 'leave.manage-delegations', 'group_name' => 'leave'],
            ['name' => 'holiday.create', 'group_name' => 'holiday'],
            ['name' => 'holiday.edit', 'group_name' => 'holiday'],
            ['name' => 'holiday.delete', 'group_name' => 'holiday'],
            ['name' => 'holiday.view', 'group_name' => 'holiday'],
            ['name' => 'holiday.export', 'group_name' => 'holiday'],
            ['name' => 'holiday.import', 'group_name' => 'holiday'],
            ['name' => 'holiday.manage-categories', 'group_name' => 'holiday'],
            ['name' => 'holiday.view-reports', 'group_name' => 'holiday'],
            ['name' => 'holiday.manage-approvers', 'group_name' => 'holiday'],
            ['name' => 'holiday.manage-delegations', 'group_name' => 'holiday'],
            ['name' => 'reporting.view-employee-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.view-attendance-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.view-leave-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.view-holiday-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.view-performance-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.view-recruitment-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.view-finance-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.view-onboarding-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.view-custom-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.export-reports', 'group_name' => 'reporting'],
            ['name' => 'reporting.manage-report-templates', 'group_name' => 'reporting'],
            ['name' => 'attendance.view', 'group_name' => 'attendance'],
            ['name' => 'attendance.mark', 'group_name' => 'attendance'],
            ['name' => 'attendance.edit', 'group_name' => 'attendance'],
            ['name' => 'attendance.delete', 'group_name' => 'attendance'],
            ['name' => 'attendance.export', 'group_name' => 'attendance'],
            ['name' => 'attendance.import', 'group_name' => 'attendance'],
            ['name' => 'attendance.manage-shifts', 'group_name' => 'attendance'],
            ['name' => 'attendance.manage-schedules', 'group_name' => 'attendance'],
            ['name' => 'attendance.view-reports', 'group_name' => 'attendance'],
            ['name' => 'attendance.manage-approvers', 'group_name' => 'attendance'],
            ['name' => 'attendance.manage-delegations', 'group_name' => 'attendance'],
            ['name' => 'payroll.view', 'group_name' => 'payroll'],
            ['name' => 'payroll.process', 'group_name' => 'payroll'],
            ['name' => 'payroll.edit', 'group_name' => 'payroll'],
            ['name' => 'payroll.delete', 'group_name' => 'payroll'],
            ['name' => 'payroll.export', 'group_name' => 'payroll'],
            ['name' => 'payroll.import', 'group_name' => 'payroll'],
            ['name' => 'payroll.manage-salaries', 'group_name' => 'payroll'],
            ['name' => 'payroll.manage-benefits', 'group_name' => 'payroll'],
            ['name' => 'payroll.view-reports', 'group_name' => 'payroll'],
            ['name' => 'payroll.manage-approvers', 'group_name' => 'payroll'],
            ['name' => 'payroll.manage-delegations', 'group_name' => 'payroll'],
            ['name' => 'hr-settings.manage', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.view', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.edit', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.delete', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.export', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.import', 'group_name' => 'hr-settings'],
            
            ['name' => 'hr-settings.manage-departments', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.manage-teams', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.manage-roles', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.manage-permissions', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.view-activity-logs', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.manage-approvers', 'group_name' => 'hr-settings'],
            ['name' => 'hr-settings.manage-delegations', 'group_name' => 'hr-settings'],

            ['name' => 'manage master data', 'group_name' => 'master-data'],
            ['name' => 'master-data.view-master-data', 'group_name' => 'master-data'],
            ['name' => 'master-data.create-master-data', 'group_name' => 'master-data'],
            ['name' => 'master-data.edit-master-data', 'group_name' => 'master-data'],
            ['name' => 'master-data.delete-master-data', 'group_name' => 'master-data'],

            ['name' => 'manage shift swaps', 'group_name' => 'shift-swaps'],
            ['name' => 'shift-swaps.view-shift-swaps', 'group_name' => 'shift-swaps'],
            ['name' => 'shift-swaps.create-shift-swap', 'group_name' => 'shift-swaps'],
            ['name' => 'shift-swaps.edit-shift-swap', 'group_name' => 'shift-swaps'],
            ['name' => 'shift-swaps.delete-shift-swap', 'group_name' => 'shift-swaps'],

            ['name' => 'dashboard.view', 'group_name' => 'dashboard'],
            ['name' => 'view-dashboard', 'group_name' => 'dashboard'],
            ['name' => 'manage-users', 'group_name' => 'admin'],
            ['name' => 'manage-roles', 'group_name' => 'admin'],
            ['name' => 'manage-permissions', 'group_name' => 'admin'],
            ['name' => 'manage-clients', 'group_name' => 'admin'],
            ['name' => 'manage-teams', 'group_name' => 'admin'],
            ['name' => 'manage-projects', 'group_name' => 'admin'],
            ['name' => 'view-projects', 'group_name' => 'admin'],
            ['name' => 'view-project-details', 'group_name' => 'admin'],
            ['name' => 'manage-project-follow-ups', 'group_name' => 'admin'],
            ['name' => 'manage-project-status-updates', 'group_name' => 'admin'],
            ['name' => 'manage-project-progress-updates', 'group_name' => 'admin'],
            ['name' => 'view-project-follow-ups', 'group_name' => 'admin'],
            ['name' => 'view-project-status-updates', 'group_name' => 'admin'],
            ['name' => 'view-project-progress-updates', 'group_name' => 'admin'],
            ['name' => 'manage-all-projects', 'group_name' => 'admin'],
            ['name' => 'view-all-projects', 'group_name' => 'admin'],
            ['name' => 'view-all-project-details', 'group_name' => 'admin'],
            ['name' => 'manage-all-project-follow-ups', 'group_name' => 'admin'],
            ['name' => 'manage-all-project-status-updates', 'group_name' => 'admin'],
            ['name' => 'manage-all-project-progress-updates', 'group_name' => 'admin'],
            ['name' => 'view-all-project-follow-ups', 'group_name' => 'admin'],
            ['name' => 'view-all-project-status-updates', 'group_name' => 'admin'],
            ['name' => 'view-all-project-progress-updates', 'group_name' => 'admin'],
            ['name' => 'access-admin-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-hr-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-finance-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-recruitment-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-performance-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-onboarding-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-attendance-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-leave-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-holiday-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-payroll-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-reporting-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-employee-dashboard', 'group_name' => 'admin'],
            ['name' => 'access-hr-settings', 'group_name' => 'admin'],
            ['name' => 'user-profile', 'group_name' => 'user'],
            ['name' => 'edit-profile', 'group_name' => 'user'],
            ['name' => 'change-password', 'group_name' => 'user'],
            ['name' => 'view-activity-logs', 'group_name' => 'user'],

        ];

        foreach ($permissions as $attributes) {
            $permission = Permission::findOrCreate($attributes['name'], 'web');

            if ($permission->group_name !== $attributes['group_name']) {
                $permission->group_name = $attributes['group_name'];
                $permission->save();
            }
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
