<?php

namespace App\Services\HR;

use App\Models\AttendancePayrollPeriod;
use App\Models\AttendancePayrollReprocessingLog;
use App\Models\AttendancePayrollSummary;
use App\Models\AttendanceAuditLog;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class AttendancePayrollService
{
    public function createPeriod(array $data, int $actorId): AttendancePayrollPeriod { return AttendancePayrollPeriod::create(array_merge($data,['status'=>'open','created_by'=>$actorId,'updated_by'=>$actorId])); }

    public function process(AttendancePayrollPeriod $period, int $actorId, ?string $reason=null): int
    {
        return DB::transaction(function() use($period,$actorId,$reason){$period=AttendancePayrollPeriod::whereKey($period->id)->lockForUpdate()->firstOrFail();$this->assertProcessable($period);$period->update(['status'=>'processing','updated_by'=>$actorId]);$old=$period->summaries()->get()->keyBy('user_id');$period->summaries()->delete();$rows=$this->aggregate($period);$count=0;foreach($rows as $row){$summary=AttendancePayrollSummary::create(array_merge((array)$row,['attendance_payroll_period_id'=>$period->id,'status'=>'draft']));if($old->has($summary->user_id))AttendancePayrollReprocessingLog::create(['attendance_payroll_period_id'=>$period->id,'user_id'=>$summary->user_id,'action'=>'reprocess','previous_values'=>$old[$summary->user_id]->toArray(),'new_values'=>$summary->toArray(),'reason'=>$reason,'created_by'=>$actorId]);$count++;}$period->update(['status'=>'review','updated_by'=>$actorId]);return $count;});
    }

    public function finalize(AttendancePayrollPeriod $period, int $actorId): AttendancePayrollPeriod
    { return DB::transaction(function()use($period,$actorId){$period=AttendancePayrollPeriod::whereKey($period->id)->lockForUpdate()->firstOrFail();abort_unless(in_array($period->status,['review','processing'],true),422,'Only a processed period can be finalized.');abort_if(!$period->summaries()->exists(),422,'The period has no payroll attendance summaries.');$period->summaries()->update(['status'=>'finalized','finalized_at'=>now(),'finalized_by'=>$actorId]);$period->update(['status'=>'finalized','updated_by'=>$actorId]);AttendancePayrollReprocessingLog::create(['attendance_payroll_period_id'=>$period->id,'action'=>'finalize','reason'=>'Payroll attendance period finalized','created_by'=>$actorId]);AttendanceAuditLog::create(['user_id'=>$actorId,'action'=>'attendance_payroll_finalized','new_values'=>$period->toArray(),'performed_at'=>now(),'source'=>'payroll']);return $period->fresh();}); }

    public function lock(AttendancePayrollPeriod $period, int $actorId): AttendancePayrollPeriod
    { return DB::transaction(function()use($period,$actorId){$period=AttendancePayrollPeriod::whereKey($period->id)->lockForUpdate()->firstOrFail();abort_unless($period->status==='finalized',422,'Only finalized periods can be locked.');$period->update(['status'=>'locked','locked_at'=>now(),'locked_by'=>$actorId,'updated_by'=>$actorId]);AttendancePayrollReprocessingLog::create(['attendance_payroll_period_id'=>$period->id,'action'=>'lock','reason'=>'Payroll attendance period locked','created_by'=>$actorId]);AttendanceAuditLog::create(['user_id'=>$actorId,'action'=>'attendance_locked','new_values'=>$period->toArray(),'performed_at'=>now(),'source'=>'payroll']);return $period->fresh();}); }

    public function reopen(AttendancePayrollPeriod $period, int $actorId, string $reason): AttendancePayrollPeriod
    { return DB::transaction(function()use($period,$actorId,$reason){$period=AttendancePayrollPeriod::whereKey($period->id)->lockForUpdate()->firstOrFail();abort_unless(in_array($period->status,['locked','finalized'],true),422,'Only finalized or locked periods can be reopened.');$period->update(['status'=>'reopened','reopened_at'=>now(),'reopened_by'=>$actorId,'remarks'=>$reason,'updated_by'=>$actorId]);AttendancePayrollReprocessingLog::create(['attendance_payroll_period_id'=>$period->id,'action'=>'reopen','reason'=>$reason,'created_by'=>$actorId]);AttendanceAuditLog::create(['user_id'=>$actorId,'action'=>'attendance_reopened','new_values'=>$period->toArray(),'reason'=>$reason,'performed_at'=>now(),'source'=>'payroll']);return $period->fresh();}); }

    public function summaries(AttendancePayrollPeriod $period, array $filters=[]){$q=$period->summaries()->with(['employee.department','employee.company','employee.branch']);foreach(['company_id','branch_id','division_id','department_id','section_id','unit_id','designation_id','employment_type_id'] as $field)if(!empty($filters[$field]))$q->where($field,$filters[$field]);if(!empty($filters['employee']))$q->where('user_id',$filters['employee']);return $q->orderBy('user_id')->paginate(25)->withQueryString();}

    public function export(AttendancePayrollPeriod $period): \Generator { foreach($period->summaries()->with('employee')->lazyById(500) as $summary)yield[$summary->employee?->employee_id,$summary->employee?->name,$period->period_name,$summary->working_days,$summary->final_payable_days,$summary->unpaid_absence_days+$summary->unpaid_leave_days,$summary->paid_leave_days,$summary->unpaid_leave_days,$summary->deduction_days,$summary->deduction_days,$summary->overtime_hours,$summary->status]; }

    protected function aggregate(AttendancePayrollPeriod $period): array { $rows=DB::table('attendance_daily_records as a')->join('users as u','u.id','=','a.user_id')->leftJoin('leave_applications as la','la.id','=','a.leave_application_id')->leftJoin('leave_types as lt','lt.id','=','la.leave_type_id')->whereBetween('a.attendance_date',[$period->period_from->toDateString(),$period->period_to->toDateString()])->selectRaw("a.user_id,u.company_id,u.branch_id,u.division_id,u.department_id,u.section_id,u.unit_id,u.designation_id,u.employment_type_id,SUM(a.attendance_status NOT IN ('weekly_off','holiday','not_applicable')) working_days,SUM(a.attendance_status IN ('present','late','early_out','late_early_out')) present_days,SUM(a.attendance_status='absent') absent_days,SUM(CASE WHEN a.attendance_status='leave' AND lt.is_paid=1 THEN 1 ELSE 0 END) paid_leave_days,SUM(CASE WHEN a.attendance_status='leave' AND COALESCE(lt.is_paid,0)=0 THEN 1 ELSE 0 END) unpaid_leave_days,SUM(a.attendance_status='weekly_off') weekly_off_days,SUM(a.attendance_status='holiday') holiday_days,SUM(a.attendance_status='half_day') half_days,SUM(a.attendance_status IN ('late','late_early_out')) late_occurrences,SUM(a.late_minutes) late_minutes,SUM(a.attendance_status IN ('early_out','late_early_out')) early_out_occurrences,SUM(a.early_out_minutes) early_out_minutes,SUM(CASE WHEN a.attendance_status='absent' OR (a.attendance_status='leave' AND COALESCE(lt.is_paid,0)=0) THEN 1 WHEN a.attendance_status='half_day' THEN .5 ELSE 0 END) unpaid_absence_days,SUM(CASE WHEN a.attendance_status IN ('present','late','early_out','late_early_out') THEN 1 WHEN a.attendance_status='leave' AND lt.is_paid=1 THEN 1 WHEN a.attendance_status='half_day' THEN .5 WHEN a.attendance_status IN ('weekly_off','holiday') THEN 1 ELSE 0 END) final_payable_days,SUM(CASE WHEN a.approved_overtime_minutes>0 THEN a.approved_overtime_minutes ELSE 0 END)/60 overtime_hours")->groupBy('a.user_id','u.company_id','u.branch_id','u.division_id','u.department_id','u.section_id','u.unit_id','u.designation_id','u.employment_type_id')->get();return $rows->map(function($r){$r=(array)$r;$r['payable_days']=$r['final_payable_days'];$r['deduction_days']=0;return $r;})->all(); }
    protected function assertProcessable(AttendancePayrollPeriod $period): void { abort_if($period->isLocked(),422,'This attendance payroll period is locked. Reopen it before reprocessing.');abort_if(in_array($period->status,['finalized'],true),422,'This period is finalized. Reopen it before reprocessing.'); }
}
