<?php
namespace App\Http\Controllers\HR;
use App\Http\Controllers\Controller; use App\Models\AttendancePolicy; use App\Models\AttendancePolicyRule; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Inertia\Inertia; use Inertia\Response;
class AttendancePolicyController extends Controller
{
    public function index(Request $request): Response { $policies=AttendancePolicy::with('rules')->when($request->filled('search'),fn($q)=>$q->where(fn($x)=>$x->where('policy_name','like','%'.$request->string('search').'%')->orWhere('policy_code','like','%'.$request->string('search').'%')))->when($request->filled('status'),fn($q)=>$q->where('status',$request->string('status')))->latest()->paginate(15)->withQueryString(); return Inertia::render('HR/Attendance/Policies/Index',['policies'=>$policies,'filters'=>$request->only('search','status')]); }
    public function store(Request $request) { $data=$this->validatePolicy($request); DB::transaction(function() use($request,$data){ $rules=$data['rules']??[]; unset($data['rules']); $policy=AttendancePolicy::create(array_merge($data,['created_by'=>$request->user()->id])); $policy->rules()->create($this->rules($rules)); }); return back()->with('success','Attendance policy created.'); }
    public function update(Request $request, AttendancePolicy $attendancePolicy) { $data=$this->validatePolicy($request,$attendancePolicy); DB::transaction(function() use($request,$data,$attendancePolicy){ $rules=$data['rules']??[]; unset($data['rules']); $attendancePolicy->update(array_merge($data,['updated_by'=>$request->user()->id])); $attendancePolicy->rules()->updateOrCreate([], $this->rules($rules)); }); return back()->with('success','Attendance policy updated.'); }
    public function destroy(AttendancePolicy $attendancePolicy) { abort_if($attendancePolicy->assignments()->exists(),422,'Cannot delete a policy with assignments.'); $attendancePolicy->delete(); return back()->with('success','Attendance policy deleted.'); }
    protected function validatePolicy(Request $request, ?AttendancePolicy $policy=null): array { return $request->validate(['policy_name'=>['required','string','max:255'],'policy_code'=>['required','string','max:100','unique:attendance_policies,policy_code,'.($policy?->id)],'description'=>['nullable','string'],'effective_from'=>['required','date'],'effective_to'=>['nullable','date','after_or_equal:effective_from'],'status'=>['required','in:active,inactive'],'rules'=>['nullable','array']]); }
    protected function rules(array $r): array { $keys=['expected_working_hours','minimum_working_hours','maximum_working_hours','late_grace_minutes','early_out_grace_minutes','late_threshold_minutes','early_out_threshold_minutes','late_affects_status','early_out_affects_status','half_day_threshold_hours','minimum_required_hours','overtime_allowed','minimum_overtime_minutes','overtime_rounding_rule','maximum_overtime_minutes','minimum_punches','maximum_punches','allow_multiple_punches','missing_punch_handling','allow_cross_midnight','maximum_attendance_span_minutes','allow_holiday_attendance','allow_weekly_off_attendance','holiday_weekly_off_overtime','settings']; return array_intersect_key($r,array_flip($keys)); }
}
