<?php
namespace App\Http\Controllers\HR;
use App\Http\Controllers\Controller;
use App\Jobs\ProcessAttendanceDeviceLogJob;
use App\Jobs\SyncAttendanceDeviceJob;
use App\Models\AttendanceDevice;
use App\Models\AttendanceDeviceEmployeeMapping;
use App\Models\AttendanceDeviceLog;
use App\Models\AttendanceDeviceSyncLog;
use App\Models\User;
use App\Models\MasterDataItem;
use App\Services\HR\AttendanceAuditService;
use App\Services\HR\AttendanceDeviceAdapterManager;
use App\Services\HR\AttendanceDeviceLogService;
use App\Services\HR\AttendanceDeviceMappingService;
use App\Services\HR\AttendanceDeviceService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
class AttendanceDeviceIntegrationController extends Controller {
 public function devices(Request $request){$q=AttendanceDevice::withCount(['mappings','logs','syncLogs'])->latest()->when($request->search,fn($q,$v)=>$q->where(fn($q)=>$q->where('device_name','like',"%$v%")->orWhere('device_code','like',"%$v%")->orWhere('ip_address','like',"%$v%")))->when($request->vendor,fn($q,$v)=>$q->where('vendor',$v))->when($request->device_type,fn($q,$v)=>$q->where('device_type',$v))->when($request->status,fn($q,$v)=>$q->where('status',$v))->when($request->company_id,fn($q,$v)=>$q->where('company_id',$v))->when($request->branch_id,fn($q,$v)=>$q->where('branch_id',$v));return Inertia::render('HR/Attendance/DeviceIntegration/Index',['tab'=>'devices','devices'=>$q->paginate(20)->withQueryString(),'deviceFilters'=>$request->only(['search','vendor','device_type','status','company_id','branch_id']),'deviceOptions'=>['vendors'=>AttendanceDevice::whereNotNull('vendor')->distinct()->orderBy('vendor')->pluck('vendor'),'types'=>['biometric','api','webhook','file_import','manual','other'],'companies'=>MasterDataItem::where('category',MasterDataItem::CATEGORY_COMPANY)->orderBy('name')->get(['id','name']),'branches'=>MasterDataItem::where('category',MasterDataItem::CATEGORY_BRANCH)->orderBy('name')->get(['id','name'])]]);}
 public function createDevice(){return Inertia::render('HR/Attendance/DeviceIntegration/DeviceForm',['device'=>null,'organizations'=>$this->organizations()]);}
 public function showDevice(AttendanceDevice $device){$device->loadCount(['mappings','logs','syncLogs']);$last=$device->syncLogs()->latest('started_at')->first();$failed=$device->syncLogs()->where('status','failed')->latest('started_at')->first();return Inertia::render('HR/Attendance/DeviceIntegration/DeviceShow',['device'=>$device,'lastSync'=>$last,'lastFailedSync'=>$failed]);}
 public function editDevice(AttendanceDevice $device){$device->loadCount(['mappings','logs','syncLogs']);return Inertia::render('HR/Attendance/DeviceIntegration/DeviceForm',['device'=>$device,'organizations'=>$this->organizations()]);}
 public function store(Request $request,AttendanceDeviceService $service,AttendanceAuditService $audit){$data=$this->deviceData($request);$device=$service->create($data,$request->user()->id);$audit->record('attendance_device_created',['new_values'=>$device->toArray(),'source'=>'device_integration']);return redirect()->route('hr.attendance.device-integration.devices')->with('success','Attendance device created.');}
 public function update(Request $request,AttendanceDevice $device,AttendanceDeviceService $service,AttendanceAuditService $audit){$data=$this->deviceData($request,true);$old=$device->toArray();$device=$service->update($device,$data,$request->user()->id);$audit->record('attendance_device_updated',['old_values'=>$old,'new_values'=>$device->toArray(),'source'=>'device_integration']);return redirect()->route('hr.attendance.device-integration.devices')->with('success','Attendance device updated.');}
 public function toggle(Request $request,AttendanceDevice $device,AttendanceDeviceService $service,AttendanceAuditService $audit){$old=$device->status;$device=$old==='active'?$service->deactivate($device,$request->user()->id):$service->activate($device,$request->user()->id);$audit->record($device->status==='active'?'attendance_device_activated':'attendance_device_deactivated',['old_values'=>['status'=>$old],'new_values'=>['status'=>$device->status],'source'=>'device_integration']);return back()->with('success','Device status updated.');}
 public function destroy(Request $request,AttendanceDevice $device,AttendanceDeviceService $service,AttendanceAuditService $audit){$old=$device->toArray();$service->delete($device);$audit->record('attendance_device_deleted',['old_values'=>$old,'source'=>'device_integration']);return back()->with('success','Attendance device removed.');}
 private function deviceData(Request $request,bool $editing=false): array {$data=$request->validate(['device_code'=>($editing?'sometimes|':'').'required|string|max:100','device_name'=>'required|string|max:150','vendor'=>'required|string|max:100','device_type'=>'required|in:biometric,api,webhook,file_import,manual,other','model'=>'nullable|string|max:100','serial_number'=>'nullable|string|max:150','connection_type'=>'required|string','protocol'=>'nullable|string|max:30','ip_address'=>'nullable|string|max:255','port'=>'nullable|integer|min:1|max:65535','connection_timeout'=>'nullable|integer|min:1|max:300','http_method'=>'nullable|string|max:10','authentication_type'=>'nullable|string|max:30','api_url'=>'nullable|url','api_key'=>'nullable|string','api_secret'=>'nullable|string','username'=>'nullable|string','password'=>'nullable|string','import_format'=>'nullable|string|max:30','file_path'=>'nullable|string|max:500','delimiter'=>'nullable|string|max:10','timezone'=>'required|string|max:80','location'=>'nullable|string|max:150','company_id'=>'nullable|exists:master_data_items,id','branch_id'=>'nullable|exists:master_data_items,id','sync_mode'=>'required|in:manual,scheduled,webhook,hybrid','auto_sync_enabled'=>'nullable|boolean','sync_frequency'=>'required|in:manual,5,10,15,30,hourly','status'=>'required|in:active,inactive','remarks'=>'nullable|string|max:2000','description'=>'nullable|string|max:2000']);if($data['device_type']==='biometric'&&empty($data['ip_address']))throw ValidationException::withMessages(['ip_address'=>'Host or IP Address is required for biometric devices.']);if(in_array($data['device_type'],['api','webhook'],true)&&empty($data['api_url']))throw ValidationException::withMessages(['api_url'=>'API Base URL is required for API/webhook devices.']);foreach(['api_key','api_secret','username','password'] as $secret)if($editing&&(!isset($data[$secret])||$data[$secret]===''))unset($data[$secret]);return $data;}
 private function organizations(){return ['companies'=>MasterDataItem::where('category',MasterDataItem::CATEGORY_COMPANY)->orderBy('name')->get(['id','name']),'branches'=>MasterDataItem::where('category',MasterDataItem::CATEGORY_BRANCH)->orderBy('name')->get(['id','name'])];}
 public function mappings(Request $request){$q=AttendanceDeviceEmployeeMapping::with(['device','user'])->withCount('logs')->latest();$q->when($request->device_id,fn($q,$v)=>$q->where('device_id',$v))->when($request->status,fn($q,$v)=>$q->where('status',$v))->when($request->effective_date,fn($q,$v)=>$q->whereDate('effective_from','<=',$v)->where(fn($q)=>$q->whereNull('effective_to')->orWhereDate('effective_to','>=',$v)))->when($request->search,fn($q,$v)=>$q->where(fn($q)=>$q->where('external_employee_id','like',"%$v%")->orWhereHas('user',fn($q)=>$q->where('employee_id','like',"%$v%")->orWhere('name','like',"%$v%")->orWhere('email','like',"%$v%"))));return Inertia::render('HR/Attendance/DeviceIntegration/Index',['tab'=>'mappings','mappings'=>$q->paginate(25)->withQueryString(),'devices'=>AttendanceDevice::where('status','active')->orderBy('device_name')->get(['id','device_name','device_code','vendor','location']),'filters'=>$request->only(['device_id','status','effective_date','search'])]);}
 public function createMapping(){return Inertia::render('HR/Attendance/DeviceIntegration/MappingForm',['mapping'=>null,'devices'=>AttendanceDevice::where('status','active')->orderBy('device_name')->get(['id','device_name','device_code','vendor','location']),'employees'=>$this->employeeOptions()]);}
 public function editMapping(AttendanceDeviceEmployeeMapping $mapping){$mapping->load(['device','user']);return Inertia::render('HR/Attendance/DeviceIntegration/MappingForm',['mapping'=>$mapping,'devices'=>AttendanceDevice::where('status','active')->orWhereKey($mapping->device_id)->orderBy('device_name')->get(['id','device_name','device_code','vendor','location']),'employees'=>$this->employeeOptions($mapping->user_id)]);}
 public function employeeSearch(Request $request){$term=$request->string('search')->toString();return response()->json(User::query()->where('status',User::STATUS_ACTIVE)->when($term,fn($q)=>$q->where(fn($q)=>$q->where('employee_id','like',"%$term%")->orWhere('name','like',"%$term%")->orWhere('email','like',"%$term%")))->orderBy('employee_id')->paginate(20));}
 public function storeMapping(Request $request,AttendanceDeviceMappingService $service,AttendanceAuditService $audit){$data=$request->validate(['device_id'=>'required|exists:attendance_devices,id','user_id'=>'required|exists:users,id','external_employee_id'=>'required|string|max:150','external_user_code'=>'nullable|string|max:150','effective_from'=>'required|date','effective_to'=>'nullable|date|after_or_equal:effective_from','status'=>'required|in:active,inactive','remarks'=>'nullable|string|max:2000']);$mapping=$service->create($data,$request->user()->id);$audit->record('attendance_device_mapping_created',['employee_id'=>$mapping->user_id,'new_values'=>$mapping->toArray(),'source'=>'device_integration']);return redirect()->route('hr.attendance.device-integration.mappings')->with('success','Employee mapping created.');}
 public function updateMapping(Request $request,AttendanceDeviceEmployeeMapping $mapping,AttendanceDeviceMappingService $service,AttendanceAuditService $audit){$data=$request->validate(['device_id'=>'required|exists:attendance_devices,id','user_id'=>'required|exists:users,id','external_employee_id'=>'required|string|max:150','external_user_code'=>'nullable|string|max:150','effective_from'=>'required|date','effective_to'=>'nullable|date|after_or_equal:effective_from','status'=>'required|in:active,inactive','remarks'=>'nullable|string|max:2000']);$old=$mapping->toArray();$mapping=$service->update($mapping,$data,$request->user()->id);$audit->record('attendance_device_mapping_updated',['employee_id'=>$mapping->user_id,'old_values'=>$old,'new_values'=>$mapping->toArray(),'source'=>'device_integration']);return redirect()->route('hr.attendance.device-integration.mappings')->with('success','Employee mapping updated.');}
 public function destroyMapping(Request $request,AttendanceDeviceEmployeeMapping $mapping,AttendanceDeviceMappingService $service,AttendanceAuditService $audit){$old=$mapping->toArray();$mapping=$service->deactivate($mapping,$request->user()->id);$audit->record('attendance_device_mapping_deactivated',['employee_id'=>$mapping->user_id,'old_values'=>$old,'new_values'=>$mapping->toArray(),'source'=>'device_integration']);return back()->with('success','Employee mapping deactivated.');}
 private function employeeOptions(?int $selected=null){return User::query()->where('status',User::STATUS_ACTIVE)->when($selected,fn($q)=>$q->orWhereKey($selected))->orderBy('employee_id')->limit(50)->get(['id','employee_id','name','email']);}
 public function logs(Request $request){$logs=AttendanceDeviceLog::with(['device','user'])->latest()->when($request->status,fn($q,$v)=>$q->where('processing_status',$v))->paginate(30)->withQueryString();return Inertia::render('HR/Attendance/DeviceIntegration/Index',['tab'=>'logs','logs'=>$logs]);}
 public function syncHistory(){return Inertia::render('HR/Attendance/DeviceIntegration/Index',['tab'=>'sync-history','syncLogs'=>AttendanceDeviceSyncLog::with('device')->latest('started_at')->paginate(25)]);}
 public function testConnection(Request $request,AttendanceDevice $device,AttendanceDeviceAdapterManager $manager,AttendanceAuditService $audit){$ok=$manager->adapter($device)->testConnection($device);$audit->record('attendance_device_connection_tested',['new_values'=>['success'=>$ok,'device_id'=>$device->id],'source'=>'device_integration']);return back()->with($ok?'success':'error',$ok?'Connection test passed.':'Connection test failed.');}
 public function sync(Request $request,AttendanceDevice $device){$data=$request->validate(['from_datetime'=>'required|date','to_datetime'=>'required|date|after_or_equal:from_datetime']);SyncAttendanceDeviceJob::dispatch($device->id,$data['from_datetime'],$data['to_datetime'],$request->user()->id,'manual');return back()->with('success','Device sync queued.');}
 public function retryLog(Request $request,AttendanceDeviceLog $log){$log->update(['processing_status'=>'pending','error_message'=>null]);ProcessAttendanceDeviceLogJob::dispatch($log->id,$request->user()->id);return back()->with('success','Device log retry queued.');}
 public function reprocessLog(Request $request,AttendanceDeviceLog $log){$log->update(['processing_status'=>'pending','error_message'=>null]);ProcessAttendanceDeviceLogJob::dispatch($log->id,$request->user()->id);return back()->with('success','Device log reprocessing queued.');}
 public function webhook(Request $request,string $deviceCode,AttendanceDeviceLogService $logs){$device=AttendanceDevice::where('device_code',$deviceCode)->where('status','active')->firstOrFail();$key=(string)$request->header('X-Device-Key');if(!$key||!hash_equals((string)($device->api_secret?:$device->api_key),$key))return response()->json(['message'=>'Unauthorized device.'],401);try{$payload=$request->validate(['employee_identifier'=>'required_without:employee_id|string','employee_id'=>'required_without:employee_identifier|string','timestamp'=>'required_without:punch_datetime|date','punch_datetime'=>'required_without:timestamp|date','punch_type'=>'nullable|string','verification_type'=>'nullable|string','verification'=>'nullable|string','external_log_id'=>'nullable|string']);$log=$logs->ingest($device,$payload);ProcessAttendanceDeviceLogJob::dispatch($log->id);return response()->json(['accepted'=>true,'duplicate'=>$log->is_duplicate],202);}catch(\Illuminate\Validation\ValidationException $e){return response()->json(['message'=>'Invalid attendance payload.','errors'=>$e->errors()],422);}catch(\Throwable $e){return response()->json(['message'=>'Attendance event could not be accepted.'],422);}}
}
