<?php
namespace App\Http\Controllers\HR;
use App\Http\Controllers\Controller; use App\Models\AttendancePolicy; use App\Models\AttendancePolicyAssignment; use App\Models\MasterDataItem; use App\Models\User; use Illuminate\Http\Request; use Inertia\Inertia; use Inertia\Response;
class AttendancePolicyAssignmentController extends Controller
{
    public function index(): Response { return Inertia::render('HR/Attendance/Assignments/Index',['assignments'=>AttendancePolicyAssignment::with(['policy','employee'])->latest()->paginate(20),'policies'=>AttendancePolicy::where('status','active')->orderBy('policy_name')->get(['id','policy_name']),'options'=>$this->options()]); }
    public function store(Request $request) { $data=$this->validateAssignment($request); $this->assertNoOverlap($data); AttendancePolicyAssignment::create(array_merge($data,['created_by'=>$request->user()->id])); return back()->with('success','Attendance policy assignment created.'); }
    public function update(Request $request, AttendancePolicyAssignment $attendancePolicyAssignment) { $data=$this->validateAssignment($request); $this->assertNoOverlap($data,$attendancePolicyAssignment); $attendancePolicyAssignment->update(array_merge($data,['updated_by'=>$request->user()->id])); return back()->with('success','Attendance policy assignment updated.'); }
    public function destroy(AttendancePolicyAssignment $attendancePolicyAssignment) { $attendancePolicyAssignment->delete(); return back()->with('success','Attendance policy assignment deleted.'); }
    protected function validateAssignment(Request $request): array { return $request->validate(['attendance_policy_id'=>['required','exists:attendance_policies,id'],'company_id'=>['nullable','exists:master_data_items,id'],'branch_id'=>['nullable','exists:master_data_items,id'],'division_id'=>['nullable','exists:master_data_items,id'],'department_id'=>['nullable','exists:master_data_items,id'],'section_id'=>['nullable','exists:master_data_items,id'],'unit_id'=>['nullable','exists:master_data_items,id'],'designation_id'=>['nullable','exists:master_data_items,id'],'employment_type'=>['nullable','string','max:255'],'user_id'=>['nullable','exists:users,id'],'effective_from'=>['required','date'],'effective_to'=>['nullable','date','after_or_equal:effective_from'],'status'=>['required','in:active,inactive'],'remarks'=>['nullable','string']]); }
    protected function assertNoOverlap(array $data, ?AttendancePolicyAssignment $ignore=null): void { $q=AttendancePolicyAssignment::where('status','active')->when($ignore,fn($x)=>$x->where('id','!=',$ignore->id)); foreach(['user_id','company_id','branch_id','division_id','department_id','section_id','unit_id','designation_id','employment_type'] as $field) { $value=$data[$field]??null; $q=$value===null?$q->whereNull($field):$q->where($field,$value); } $q=$q->where('effective_from','<=', $data['effective_to']??'9999-12-31')->where(fn($x)=>$x->whereNull('effective_to')->orWhere('effective_to','>=',$data['effective_from'])); abort_if($q->exists(),422,'The attendance policy assignment overlaps an existing assignment.'); }
    protected function options(): array { $item=fn($c)=>MasterDataItem::where('category',$c)->where('status','active')->orderBy('name')->get(['id','parent_id','name','code']); return ['companies'=>$item('company'),'branches'=>$item('branch'),'divisions'=>$item('division'),'departments'=>$item('department'),'sections'=>$item('section'),'units'=>$item('unit'),'designations'=>$item('designation'),'employmentTypes'=>$item('employee_type'),'employees'=>User::where('status','active')->orderBy('name')->get(['id','name','employee_id'])]; }
}
