import { Head, Link } from '@inertiajs/react';
import HRLayout from '@/Layouts/HRLayout';
import { useEffect, useMemo, useState } from 'react';

const REPORTS = { balance: 'Leave Balance', ledger: 'Leave Ledger', history: 'Employee Leave History', department: 'Department-wise Leave', monthly: 'Monthly Leave', utilization: 'Leave Utilization' };
const FIELDS = ['company_id', 'branch_id', 'division_id', 'department_id', 'section_id', 'unit_id', 'designation_id', 'leave_type_id'];

export default function Index({ report = 'dashboard', filters = {}, options = {}, cards = [] }) {
    const [active, setActive] = useState(REPORTS[report] ? report : 'dashboard');
    const [form, setForm] = useState({ as_of_date: new Date().toISOString().slice(0, 10), year: new Date().getFullYear(), per_page: 25, ...filters });
    const [data, setData] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
    const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
    const dependent = (key, parent) => (options[key] || []).filter((item) => !parent || String(item.parent_id || '') === String(parent));
    const params = useMemo(() => Object.fromEntries(Object.entries({ ...form, report: active }).filter(([, value]) => value !== '' && value !== null && value !== undefined)), [form, active]);
    const load = async () => { setLoading(true); setError(''); try { const res = await fetch(route('hr.leave.reports.data') + '?' + new URLSearchParams(params)); const json = await res.json(); if (!res.ok) throw new Error(json.message || 'Unable to load report.'); setData(json); } catch (e) { setError(e.message); } finally { setLoading(false); } };
    useEffect(() => { if (active !== 'dashboard') load(); }, [active]);
    const exportUrl = route('hr.leave.reports.export') + '?' + new URLSearchParams(params);
    return <HRLayout heading="Leave Reports & Analytics" subheading="Read-only, ledger-backed reporting with organizational scope and exportable results."><Head title="Leave Reports & Analytics" /><div className="space-y-6">
        {active === 'dashboard' ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cards.map((card) => <button key={card.key} onClick={() => setActive(card.key)} className="rounded-3xl border border-slate-200 bg-white p-6 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-sky-300"><p className="text-lg font-semibold text-slate-900">{card.title}</p><p className="mt-2 text-sm leading-6 text-slate-500">{card.description}</p><span className="mt-5 inline-block text-sm font-semibold text-sky-700">Open report →</span></button>)}</div> : <>
            <div className="flex flex-wrap items-center gap-2">{Object.entries(REPORTS).map(([key, label]) => <button key={key} onClick={() => setActive(key)} className={`rounded-full px-4 py-2 text-sm font-semibold ${active === key ? 'bg-slate-900 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{label}</button>)}</div>
            <form onSubmit={(e) => { e.preventDefault(); load(); }} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <Select label="Company" value={form.company_id} onChange={(v) => { set('company_id', v); set('branch_id', ''); }} options={options.companies} />
                <Select label="Branch" value={form.branch_id} onChange={(v) => set('branch_id', v)} options={dependent('branches', form.company_id)} />
                <Select label="Division" value={form.division_id} onChange={(v) => set('division_id', v)} options={dependent('divisions', form.branch_id || form.company_id)} />
                <Select label="Department" value={form.department_id} onChange={(v) => set('department_id', v)} options={dependent('departments', form.division_id || form.branch_id || form.company_id)} />
                <Select label="Section" value={form.section_id} onChange={(v) => set('section_id', v)} options={dependent('sections', form.department_id || form.division_id || form.branch_id || form.company_id)} />
                <Select label="Unit" value={form.unit_id} onChange={(v) => set('unit_id', v)} options={dependent('units', form.section_id || form.department_id || form.division_id || form.branch_id || form.company_id)} />
                <Select label="Leave Type" value={form.leave_type_id} onChange={(v) => set('leave_type_id', v)} options={options.leaveTypes} leave />
                <Field label="Employee"><input className="input" value={form.employee || ''} onChange={(e) => set('employee', e.target.value)} placeholder="Name or ID" /></Field>
                {active === 'balance' && <Field label="Balance As Of"><input className="input" type="date" value={form.as_of_date || ''} onChange={(e) => set('as_of_date', e.target.value)} /></Field>}
                {['monthly', 'ledger', 'history', 'department'].includes(active) && <><Field label="From"><input className="input" type="date" value={form.from || ''} onChange={(e) => set('from', e.target.value)} /></Field><Field label="To"><input className="input" type="date" value={form.to || ''} onChange={(e) => set('to', e.target.value)} /></Field></>}
                {active === 'monthly' && <Field label="Year"><input className="input" type="number" value={form.year || ''} onChange={(e) => set('year', e.target.value)} /></Field>}
                {active === 'ledger' && <Field label="Transaction Type"><select className="input" value={form.transaction_type || ''} onChange={(e) => set('transaction_type', e.target.value)}><option value="">All transaction types</option>{['opening', 'accrual', 'carry_forward', 'leave_approved', 'leave_cancelled', 'adjustment', 'encashment', 'expiry'].map((v) => <option key={v}>{v}</option>)}</select></Field>}
            </div><div className="mt-5 flex gap-3"><button className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">{loading ? 'Loading...' : 'Run Report'}</button><a href={exportUrl} className="rounded-xl border border-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-700">Export CSV</a><button type="button" onClick={() => { setForm({ as_of_date: new Date().toISOString().slice(0, 10), year: new Date().getFullYear(), per_page: 25 }); setData(null); }} className="text-sm text-slate-500">Clear</button></div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</form>
            {data && <ReportTable active={active} data={data} />}
        </>}
    </div></HRLayout>;
}
function Field({ label, children }) { return <div><label className="block text-sm font-medium text-slate-700">{label}</label><div className="mt-2">{children}</div></div>; }
function Select({ label, value, onChange, options = [], leave }) { return <Field label={label}><select className="input" value={value || ''} onChange={(e) => onChange(e.target.value)}><option value="">All {label}s</option>{options.map((item) => <option key={item.id} value={item.id}>{leave ? item.leave_name : item.name}</option>)}</select></Field>; }
 function ReportTable({ active, data }) { const rows = data.rows || []; const keys = { balance: ['employee_id', 'employee_name', 'leave_type', 'policy', 'opening', 'accrued', 'carry_forward', 'used', 'cancelled', 'adjustment', 'encashment', 'expiry', 'current_balance'], ledger: ['transaction_date', 'effective_date', 'employee_code', 'employee_name', 'leave_name', 'policy_name', 'transaction_type', 'transaction_source', 'transaction_reference', 'credit_days', 'debit_days', 'balance_after', 'remarks', 'performed_by_name', 'approved_by_name', 'processed_by_name'], history: ['application_no', 'employee_code', 'employee_name', 'leave_name', 'policy_name', 'start_date', 'end_date', 'total_days', 'requested_days', 'days', 'status', 'reason', 'delegate_name', 'submitted_at', 'approved_at', 'rejected_at', 'cancelled_at', 'withdrawn_at'], department: ['department', 'employee_count', 'applications', 'approved_applications', 'total_leave_days'], monthly: ['year', 'month', 'leave_name', 'applications', 'approved_days', 'rejected_days', 'cancelled_days'], utilization: ['leave_type', 'available', 'used', 'remaining', 'utilization'] }[active] || []; return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h2 className="font-semibold text-slate-900">{REPORTS[active]}</h2><p className="mt-1 text-xs text-slate-500">{data.summary?.records ?? rows.length} records · Balance reports use transaction-time ledger data.</p></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{keys.map((key) => <th key={key} className="whitespace-nowrap px-4 py-3 font-medium capitalize text-slate-600">{key.replaceAll('_', ' ')}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, index) => <tr key={row.id || index} className="hover:bg-slate-50">{keys.map((key) => <td key={key} className="whitespace-nowrap px-4 py-3 text-slate-700">{key === 'employee_name' && active === 'balance' ? <Link className="text-sky-700" href={route('hr.leave.balances.ledger', { employee: row.employee_user_id, leaveType: row.leave_type_id })}>{row[key]}</Link> : row[key] ?? '-'}</td>)}</tr>)}</tbody></table></div>{!rows.length && <p className="p-10 text-center text-sm text-slate-500">No leave records found for the selected filters.</p>}</div>; }
