<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('attendance_audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('employee_id')->nullable()->constrained('users')->nullOnDelete();$t->unsignedBigInteger('attendance_id')->nullable();$t->string('action');$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->text('reason')->nullable();$t->string('source')->nullable();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->timestamp('performed_at');$t->timestamps();$t->index(['employee_id','performed_at'],'att_audit_employee_date_idx');$t->index(['action','performed_at'],'att_audit_action_date_idx');});
  Schema::create('attendance_correction_histories',function(Blueprint $t){$t->id();$t->unsignedBigInteger('attendance_daily_record_id')->nullable();$t->foreign('attendance_daily_record_id','att_corr_daily_fk')->references('id')->on('attendance_daily_records')->nullOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('correction_type');$t->json('old_values');$t->json('new_values');$t->text('reason');$t->string('source')->default('manual');$t->foreignId('corrected_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('corrected_at');$t->string('reference_type')->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->timestamps();$t->index(['user_id','corrected_at'],'att_correction_user_date_idx');});
  Schema::create('attendance_raw_logs',function(Blueprint $t){$t->id();$t->string('employee_identifier');$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('device_id')->nullable();$t->string('punch_identifier')->nullable();$t->dateTime('punch_datetime');$t->string('punch_type')->nullable();$t->string('source');$t->string('device_location')->nullable();$t->json('raw_payload')->nullable();$t->timestamp('imported_at')->nullable();$t->string('processing_status')->default('pending');$t->text('error_message')->nullable();$t->timestamps();$t->unique(['source','punch_identifier'],'att_raw_source_punch_unique');$t->index(['employee_identifier','punch_datetime'],'att_raw_employee_date_idx');});
  Schema::create('attendance_reconciliation_records',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->date('attendance_date');$t->string('issue_type');$t->string('status')->default('open');$t->string('severity')->default('medium');$t->text('details')->nullable();$t->json('context')->nullable();$t->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('resolved_at')->nullable();$t->timestamps();$t->index(['attendance_date','status','severity'],'att_recon_status_idx');});
  Schema::create('attendance_exceptions',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->unsignedBigInteger('attendance_daily_record_id')->nullable();$t->foreign('attendance_daily_record_id','att_exception_daily_fk')->references('id')->on('attendance_daily_records')->nullOnDelete();$t->date('exception_date')->nullable();$t->string('exception_type');$t->string('severity')->default('medium');$t->string('status')->default('open');$t->string('source')->nullable();$t->text('details')->nullable();$t->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('resolved_at')->nullable();$t->timestamps();$t->index(['exception_type','status','exception_date'],'att_exception_filter_idx');});
  Schema::create('attendance_archives',function(Blueprint $t){$t->id();$t->unsignedBigInteger('attendance_daily_record_id')->nullable();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->date('attendance_date');$t->json('record_data');$t->json('organization_snapshot')->nullable();$t->foreignId('archived_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('archived_at');$t->timestamps();$t->index(['user_id','attendance_date'],'att_archive_user_date_idx');});
  Schema::create('attendance_admin_settings',function(Blueprint $t){$t->id();$t->unsignedInteger('maximum_backdated_days')->default(7);$t->boolean('employee_backdated_regularization')->default(true);$t->boolean('manager_backdated_approval')->default(true);$t->boolean('hr_can_bypass_backdate')->default(true);$t->boolean('locked_period_bypass')->default(false);$t->boolean('backdate_reason_required')->default(true);$t->unsignedInteger('archive_after_years')->nullable();$t->timestamps();});
 }
 public function down(): void {foreach(['attendance_admin_settings','attendance_archives','attendance_exceptions','attendance_reconciliation_records','attendance_raw_logs','attendance_correction_histories','attendance_audit_logs'] as $table)Schema::dropIfExists($table);}
};
