import { Head, Link, useForm } from '@inertiajs/react';
import HRLayout from '@/Layouts/HRLayout';

const types = { daily:'Daily Attendance', monthly:'Monthly Attendance', employee:'Employee Attendance', department:'Department-wise Attendance', 'late-early':'Late & Early Out', absenteeism:'Absenteeism', overtime:'Overtime', summary:'Attendance Summary' };
const formatHours = minutes => `${Math.floor((Number(minutes)||0)/60)}h ${((Number(minutes)||0)%60)}m`;

export default function Index({ type='daily', title, columns=[], rows=[], summary={}, filters={} }) {
    const form = useForm({ from: filters.from || '', to: filters.to || '', month: filters.month || '', year: filters.year || new Date().getFullYear(), employee_id: filters.employee_id || '', employee: filters.employee || '', status: filters.status || '' });
    const apply = e => { e.preventDefault(); form.get(route('hr.attendance.reports.index',{type}), { preserveState:true }); };
    const query = new URLSearchParams(Object.entries(form.data).filter(([,v])=>v !== '' && v !== null && v !== undefined)).toString();
    const exportUrl = `${route('hr.attendance.reports.export',{type})}${query ? `?${query}` : ''}`;
    const data = Array.isArray(rows) ? rows : (rows.data || []);
    const rowCells = row => {
        if (type === 'daily') return [row.user?.employee_id,row.user?.name,row.user?.company?.name,row.user?.branch?.name,row.user?.division?.name,row.user?.department?.name,row.user?.section?.name,row.user?.unit?.name,row.user?.designation?.name,row.shift?.shift_name,row.attendance_date,row.first_in?.slice?.(0,16)||'—',row.last_out?.slice?.(0,16)||'—',formatHours(row.worked_minutes),row.late_minutes,row.early_out_minutes,formatHours(row.calculated_overtime_minutes),row.attendance_status,'—',row.remarks||'—'];
        if (type === 'monthly') return [row.employee_code,row.name,row.total_days,row.present_days,row.absent_days,row.leave_days,row.holiday_days,row.weekly_off_days,row.half_days,row.late_days,row.early_out_days,row.missing_punch_days,formatHours(row.worked_minutes),formatHours(row.overtime_minutes)];
        if (type === 'department') return [row.department,row.employees,row.present_days,row.absent_days,row.leave_days,row.late_days,row.early_out_days,row.missing_punch_days,formatHours(row.overtime_minutes),`${row.attendance_percentage ?? ((row.working_days ? row.present_days/row.working_days*100:0).toFixed(2))}%`];
        if (type === 'late-early') return [row.user?.name,row.user?.department?.name,row.attendance_date,row.shift?.shift_name,row.first_in||'—',row.late_minutes,row.last_out||'—',row.early_out_minutes,'—'];
        if (type === 'absenteeism') return [row.user?.name,row.user?.department?.name,row.attendance_date,row.attendance_status,row.remarks||'—'];
        if (type === 'overtime') return [row.user?.name,row.user?.department?.name,row.attendance_date,row.shift?.shift_name,formatHours(row.scheduled_minutes),formatHours(row.worked_minutes),formatHours(row.calculated_overtime_minutes),row.attendance_status,row.remarks||'—'];
        if (type === 'summary') return [String(row.status||'').replaceAll('_',' '),row.records];
        return [row.attendance_date,row.user?.name,row.shift?.shift_name,row.first_in||'—',row.last_out||'—',formatHours(row.worked_minutes),row.late_minutes,row.early_out_minutes,formatHours(row.calculated_overtime_minutes),row.attendance_status,row.remarks||'—'];
    };
    return <HRLayout heading={title || types[type]} subheading="Read-only reporting from processed attendance results."><Head title={title || types[type]} /><div className="space-y-5"><form onSubmit={apply} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-4"><input className="input" type="date" value={form.data.from} onChange={e=>form.setData('from',e.target.value)} /><input className="input" type="date" value={form.data.to} onChange={e=>form.setData('to',e.target.value)} /><select className="input" value={form.data.month} onChange={e=>form.setData('month',e.target.value)}><option value="">Date range</option>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2000,i,1).toLocaleString('en',{month:'long'})}</option>)}</select><input className="input" type="number" value={form.data.year} onChange={e=>form.setData('year',e.target.value)} /><input className="input" placeholder="Employee ID" value={form.data.employee_id} onChange={e=>form.setData('employee_id',e.target.value)} /><select className="input" value={form.data.status} onChange={e=>form.setData('status',e.target.value)}><option value="">All statuses</option>{['present','absent','late','early_out','late_early_out','half_day','leave','weekly_off','holiday','missing_punch'].map(s=><option key={s}>{s}</option>)}</select><button className="rounded-xl bg-slate-900 px-4 py-2 text-white">Apply Filters</button><a className="rounded-xl border px-4 py-2 text-center" href={exportUrl}>Export CSV</a></form><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-6">{Object.entries(summary).map(([key,value])=><div className="rounded-xl border bg-white p-3" key={key}><div className="text-xs text-slate-500">{key.replaceAll('_',' ')}</div><div className="mt-1 text-xl font-bold">{typeof value==='number'&&key.includes('minutes')?formatHours(value):value}</div></div>)}</div><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr>{columns.map(c=><th className="whitespace-nowrap p-3 text-xs uppercase text-slate-500" key={c}>{c}</th>)}</tr></thead><tbody>{data.length===0?<tr><td className="p-8 text-center text-slate-500" colSpan={columns.length}>No processed attendance records found for the selected filters.</td></tr>:data.map((row,i)=><tr className="border-t" key={row.id||row.employee_id||i}>{rowCells(row).map((cell,j)=><td className="whitespace-nowrap p-3" key={j}>{cell ?? '—'}</td>)}</tr>)}</tbody></table></div>{rows.links&&<div className="flex flex-wrap gap-2">{rows.links.map((link,i)=><Link key={i} href={link.url||'#'} className={`rounded border px-3 py-1 text-sm ${link.active?'bg-slate-900 text-white':''}`} dangerouslySetInnerHTML={{__html:link.label}} />)}</div>}</div></HRLayout>;
}
